### ISSUE TITLE
Add User Auth

### ISSUE THREAD

**Issue by i-mighty** [i-mighty/shortUrl-API#1]
Currently there is no form of user authentication. The task is to add user auth and user jwt to authenticate each request made subsequently. 
TODOS:

- [ ] Add Login and Register functionalities.
- [ ] Add Auth middlewares.
- [ ] On fetch URLs request, If the user is authenticated, then fetch only the user-specific URLs. If not return all URLs not associated with any user. 
- [ ] If a request is made to shorten a new URL, the new entry should be associated with the user. 
- [ ] This goes without saying but write for tests for everything you add and make sure they pass. 
- [ ] When you are done, push your changes on a branch and create a PR.

There is technically no time limit to this task so feel free to submit whenever you are done. However, this task is really doable in about 10 hours max. 
Good luck and feel free to reach out to me if you need any help

**Comment by Temitope-Emmanuel** [comment]
> * [x]  Add Login and Register functionalities.
> * [x]  Add Auth middlewares.
> * [x]  On fetch URLs request, If the user is authenticated, then fetch only the user-specific URLs. If not return all URLs not associated with any user.
> * [x]  If a request is made to shorten a new URL, the new entry should be associated with the user.
> * [x]  This goes without saying but write for tests for everything you add and make sure they pass.
> * [x]  When you are done, push your changes on a branch and create a PR.
